#!/usr/bin/env node
'use strict';

/**
 * setup.js — One-time setup for Page Assistant.
 *
 * Usage:
 *   node setup.js               # Prompts for API key + generates icons
 *   node setup.js --icons-only  # Only generates icons (no key prompt)
 *   node setup.js <YOUR_KEY>    # Non-interactive: writes key directly
 */

const fs       = require('fs');
const path     = require('path');
const zlib     = require('zlib');
const readline = require('readline');

const ROOT        = __dirname;
const ICONS_ONLY  = process.argv.includes('--icons-only');
const INLINE_KEY  = process.argv.find(a => !a.startsWith('-') && a !== process.argv[0] && a !== process.argv[1]);

// ─── PNG generation (zero npm deps) ──────────────────────────────────────────

function crc32(buf) {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    table[i] = c;
  }
  let crc = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) {
    crc = table[(crc ^ buf[i]) & 0xFF] ^ (crc >>> 8);
  }
  return (crc ^ 0xFFFFFFFF) >>> 0;
}

function pngChunk(type, data) {
  const typeB      = Buffer.from(type, 'ascii');
  const lenBuf     = Buffer.alloc(4);
  lenBuf.writeUInt32BE(data.length, 0);
  const crcInput   = Buffer.concat([typeB, data]);
  const crcBuf     = Buffer.alloc(4);
  crcBuf.writeUInt32BE(crc32(crcInput), 0);
  return Buffer.concat([lenBuf, typeB, data, crcBuf]);
}

/**
 * Generate a solid-colour RGB PNG of the given size.
 * Draws a rounded-feel icon: accent-blue background, white "P" initial.
 * For simplicity, the actual content is a flat blue square — replace with a
 * proper design tool if you want something fancier.
 */
function makeSolidPNG(size, r, g, b) {
  const PNG_SIG = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);

  // IHDR
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);  // width
  ihdr.writeUInt32BE(size, 4);  // height
  ihdr[8]  = 8; // bit depth
  ihdr[9]  = 2; // colour type: RGB
  ihdr[10] = 0; // compression
  ihdr[11] = 0; // filter
  ihdr[12] = 0; // interlace

  // Raw image data: one filter byte (None=0) per row, then RGB pixels
  const rowSize = 1 + size * 3;
  const raw     = Buffer.alloc(size * rowSize, 0);

  for (let y = 0; y < size; y++) {
    const base = y * rowSize;
    raw[base] = 0; // filter: None
    for (let x = 0; x < size; x++) {
      // Draw a simple "P" letter in white on the lower-right quadrant
      // so the icon looks distinct at all sizes.
      const inLetter = isInLetterP(x, y, size);
      raw[base + 1 + x * 3] = inLetter ? 255 : r;
      raw[base + 2 + x * 3] = inLetter ? 255 : g;
      raw[base + 3 + x * 3] = inLetter ? 255 : b;
    }
  }

  const compressed = zlib.deflateSync(raw, { level: 9 });
  return Buffer.concat([
    PNG_SIG,
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', compressed),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
}

/**
 * Renders a simple blocky "P" glyph — looks reasonable at 16/48/128px.
 * Returns true if pixel (x, y) in an (size×size) canvas should be white.
 */
function isInLetterP(x, y, size) {
  const s = size;
  // Normalise to a 0-1 grid then map to a 5×7 glyph
  const col = Math.floor((x / s) * 5);
  const row = Math.floor((y / s) * 7);

  // "P" glyph on a 5×7 grid (1=white, 0=blue)
  const P = [
    [1, 1, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [1, 0, 0, 1, 0],
    [1, 1, 1, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
  ];

  if (row < 0 || row >= 7 || col < 0 || col >= 5) return false;
  return P[row][col] === 1;
}

function generateIcons() {
  const iconsDir = path.join(ROOT, 'icons');
  if (!fs.existsSync(iconsDir)) fs.mkdirSync(iconsDir, { recursive: true });

  // Accent blue: #4a7cf7 → rgb(74, 124, 247)
  for (const size of [16, 48, 128]) {
    const png  = makeSolidPNG(size, 74, 124, 247);
    const dest = path.join(iconsDir, `icon${size}.png`);
    fs.writeFileSync(dest, png);
    console.log(`  ✓ icons/icon${size}.png`);
  }
}

// ─── API-key config ───────────────────────────────────────────────────────────

function writeConfigFile(key) {
  const content = [
    '// Auto-generated by setup.js. DO NOT commit this file.',
    `const GEMINI_API_KEY = '${key}';`,
    'export default GEMINI_API_KEY;',
    '',
  ].join('\n');
  fs.writeFileSync(path.join(ROOT, 'config.js'), content, 'utf8');
  console.log('  ✓ config.js written');
}

async function promptForKey() {
  return new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    rl.question('\nPaste your Gemini API key (https://aistudio.google.com/apikey):\n> ', (ans) => {
      rl.close();
      resolve(ans.trim());
    });
  });
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n─── Page Assistant Setup ───\n');

  console.log('Generating icons…');
  generateIcons();

  if (ICONS_ONLY) {
    console.log('\nIcons generated. Run  node setup.js  to add your API key.\n');
    return;
  }

  const configPath = path.join(ROOT, 'config.js');

  if (INLINE_KEY) {
    writeConfigFile(INLINE_KEY);
  } else if (fs.existsSync(configPath)) {
    const existing = fs.readFileSync(configPath, 'utf8');
    if (!existing.includes('YOUR_GEMINI_API_KEY_HERE')) {
      console.log('\n  ℹ  config.js already contains a key — skipping prompt.');
      console.log('     Delete config.js and re-run to reset.\n');
      printNextSteps();
      return;
    }
    const key = await promptForKey();
    if (key && key !== 'YOUR_GEMINI_API_KEY_HERE') {
      writeConfigFile(key);
    } else {
      console.log('\n  ⚠  No key entered. Edit config.js manually before using the extension.\n');
    }
  } else {
    const key = await promptForKey();
    if (key && key !== 'YOUR_GEMINI_API_KEY_HERE') {
      writeConfigFile(key);
    } else {
      console.log('\n  ⚠  No key entered. Edit config.js manually before using the extension.\n');
    }
  }

  printNextSteps();
}

function printNextSteps() {
  console.log('\n─── Next steps ───────────────────────────────');
  console.log('  1. Open chrome://extensions in Chrome');
  console.log('  2. Enable "Developer mode" (top-right toggle)');
  console.log('  3. Click "Load unpacked" → select this folder');
  console.log('  4. Click the Page Assistant icon in your toolbar');
  console.log('──────────────────────────────────────────────\n');
}

main().catch(console.error);
